app:
  name: "bluebell"
  mode: "dev"
  port: 8081
  start_time: "2022-04-02"
  machine_id: 1
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "192.168.60.90"
  port: 3306
  user: "root"
  password: "403bb304"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "192.168.60.90"
  port: 6379
  password: "123456"
  db: 0
  pool_size: 100
dirtyword:
  path: "./pkg/dwf/dirty_words.txt"
file:
  base_path: "./"
  post_pic: "/upload/post_pic/"
  vedio: "/upload/vedios/"
  head_pic: "/upload/head_pic/"